"""
Django settings for Store_api project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from django.template.context_processors import media

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+=ixhvd$m-yxj+dn8oc^&&54+utngd#70)(f(zq^dh&sjdmbze'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt',
    'rest_framework',
    'drf_spectacular',
    'cachalot',  # для django-cachalot
    'cacheops',  # для django-cacheops
    'easy_thumbnails',

    'products',
    'orders',
    'shared',
    'cart',
    'contacts',
    'api_auth',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Store_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Store_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
'default': {
'ENGINE': 'django.db.backends.postgresql',
'NAME': 'shopdb',
'USER': 'postgres',
'PASSWORD': 'postgres',
'HOST': 'localhost',
'PORT': '5432',
}
}

import os

MEDIA_URL = '/media/'  # URL для доступа к медиафайлам (должен совпадать с роутингом в urls.py)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Путь к папке на сервере


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': None,      # 10 запросов/день для гостей
        'user': None,    # 100 запросов/день для авторизованных
    }
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # стандартный бэкенд
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Your Project API',
    'DESCRIPTION': 'Your project description',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}

CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'  # Redis на localhost
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# 2. Настройки easy-thumbnails
THUMBNAIL_ALIASES = {
    '': {
        'avatar_small': {'size': (100, 100), 'crop': True},
        'avatar_medium': {'size': (200, 200), 'crop': True},
        'product_thumb': {'size': (300, 300), 'crop': False},
    },
}
THUMBNAIL_BASEDIR = 'thumbnails'
THUMBNAIL_CACHE_TIMEOUT = 60 * 60 * 24  # 1 сутки
THUMBNAIL_DEBUG = False

# 3. Хранение файлов (настройка под ваш случай)
# Для локального хранения:
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Для S3 (если используете):
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# AWS_ACCESS_KEY_ID = 'ваш_ключ'
# AWS_SECRET_ACCESS_KEY = 'ваш_секрет'
# AWS_STORAGE_BUCKET_NAME = 'ваш_бакет'


CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/0',  # DB 1
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}
# Настройки для django-cachalot
CACHALOT_ENABLED = True
CACHALOT_CACHE = 'default'
CACHALOT_TABLE_WHITELIST = ['products', 'cart', 'ProductParameter','orders', 'api_auth']

# Для django-cacheops
CACHEOPS = {
    'products.*': {'ops': 'all', 'timeout': 60 * 60},  # 1 час
    'orders.*': {'ops': 'all', 'timeout': 60 * 30},  # 30 минут для заказов
    'categories.*': {'ops': 'all', 'timeout': 60 * 30},  # 30 минут для заказов
    'auth.*': {'ops': ('fetch', 'get'), 'timeout': 60 * 15},  # 15 минут
    'cart.cart': {'ops': 'all', 'timeout': 60 * 15,}, # 15 минут (можно изменить)
}